version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pr_ai_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pr_ai_db
    ports:
      - "5433:5432"

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: pr_ai_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
    - .env
    depends_on:
      - db
    environment:
      DB_HOST: db